USE sqldb;

CREATE TABLE testTBL3
(id INT AUTO_INCREMENT PRIMARY KEY,
userName CHAR(3),
age INT);
ALTER TABLE testTBL3 AUTO_INCREMENT = 1000;

SET @@auto_increment_increment=3;

INSERT INTO testTBL3 VALUES(NULL, '나연', 20);
INSERT INTO testTBL3 VALUES(NULL, '정연', 18);
INSERT INTO testTBL3 VALUES(NULL, '모모', 19);
SELECT * FROM testTBL3;